name: flutter_dev_console
description: A lightweight Flutter dev console for viewing API requests, logs, and analytics events in real time.
version: 1.0.2
repository: https://github.com/jiikawa/flutter_dev_console.git

environment:
  sdk: ^3.6.0
  flutter: ">=3.10.0"

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
