name: dev_console
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/jiang1654/startup_time_plugin.git

environment:
  sdk: ^3.6.0
  flutter: ">=3.10.0"

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
